### ISSUE TITLE
As a parking user I would like to immediately see the real-time availability of parking lots, if available

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-parking#12]
This information should be visualized already at an icon level.
Check for example https://mobility.meran.eu/, in which icons have a coloured mark to highlight the status of the parking lot (green = large availability; orange = little availability; red = no availability) - the categories are somewhere defined in the source code (e.g. green if at least x parking lots are available, and so on).
For parking data without real-time data, the same mark should be visible, but with a different colour (e.g. gray), which should be used also in case an "online" parking is currently offline (= data not available since at least 1 day).

**Comment by lcfd** [comment]
@gnurant

**Comment by Piiit** [comment]
@lcfd @GnuRant
I deployed the new version https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff

@rcavaliere Please test, can we close it?

**Comment by Piiit** [comment]
@lcfd Is this to review?
