### ISSUE TITLE
As a parking user, I would like to see how "fresh" the real-time information is

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-parking#13]
Timestamp information missing in the detail information of an "online" parking station

**Comment by lcfd** [comment]
@gnurant

**Comment by Piiit** [comment]
@lcfd @GnuRant
I deployed the new version https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff

@rcavaliere Please test, can we close it?

**Comment by Piiit** [comment]
@lcfd Is this to review?
