### ISSUE TITLE
As a parking user, I would expect an icon which is more representative of the fact that it is related to a parking station

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-parking#14]
The current icon is red and generic. Also connected to #12, the icon should be related to "parking". Please consider to use the one of https://mobility.meran.eu/

**Comment by lcfd** [comment]
@gnurant

**Comment by Piiit** [comment]
@rcavaliere @lcfd @GnuRant
I deployed the new version https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff

@rcavaliere Please test, can we close it?

**Comment by Piiit** [comment]
@lcfd If this is to review, please move it to that column. thx
