### ISSUE TITLE
Change color of the parking icon according to the occupancy

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-parking#15]
It would be nice to have the icon of the Paring lots that has real time data different from the one that hasn't real time information.

One idea it could be to use a neutral colour (eg. gray or blue) for the icon of non real time parking and for the one with real time data use green-yellow-red according to the occupancy of the parking lots.

@lcfd @GnuRant

**Comment by Piiit** [comment]
@sseppi @rcavaliere @lcfd @GnuRant
I deployed the new version https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff

@sseppi  Please test, can we close it?
