### ISSUE TITLE
As a Web component Store manager I want to have the Parking Web Component online

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-parking#2]
- [x] @Piiit Integrate webcomp into the store
- [x] @Piiit CI pipeline missing

I know this is just the first MVP, so I think we are on a good way, just wanna quickly enumerate some issues :-)

First feedback/questions:
- [x] @lcfd No tiles shown, is there something to set in .env while building/developing/watching? Webcomp has a gray overlay... How to use it with docker-compose up?
- [x] @lcfd README incomplete: switch to yarn for instance, describe all .env vars, .env.example missing
- [x] @lcfd Widht/height not properly working, overlaps and distortion...
  - [x]  @lcfd ...are they accessible via CSS? Please add a section inside the README for that also
  >> Ignored for now, if needed we could add those properties to another user story for another iteration
- [x] @lcfd the searchbox seems not working.
- [x] @sseppi wcs-manifest.json still misses some metadata

**Comment by sseppi** [comment]
I add the link to the component on our testing environment:

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff

**Comment by Piiit** [comment]
Height and width seem to work fine now, did not test it with CSS thou...  I updated the tasks above

**Comment by rcavaliere** [comment]
Guys, I see just the data coming from the ODH Mobility. What about the static parking information coming from ODH Tourism?

**Comment by lcfd** [comment]
Hi, @Piiit @sseppi @rcavaliere

>  @lcfd ...are they accessible via CSS? Please add a section inside the README for that also

No, they aren't. We are using them via properties because the component need to check the dimensions to show the content correctly. 

>   @sseppi wcs-manifest.json still misses some metadata

I suppose that this is the last remaining point.

> Guys, I see just the data coming from the ODH Mobility. What about the static parking information coming from ODH Tourism?

This is actually in PR


cc @Gnurant
