### ISSUE TITLE
Some stations do not have coordinates assigned, and thus generate undefined direction links

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-parking#20]
1) Click on directions inside the detail view
2) google maps opens with undefined,undefined coordinates

**Comment by lcfd** [comment]
@Piiit Hi, can you explain more extensively the outcome that we want to obtain?

@gnurant fyi

**Comment by lcfd** [comment]
@Piiit we will remove the link if the coordinates are undefined

**Comment by lcfd** [comment]
@Piiit I suggest you to check the API integrity.
`scoordinate` has changed. Sometimes the coordinates are expressed using `x` and `y` others with `lat` and `lng`.

@gnurant @sseppi fyi

**Comment by Piiit** [comment]
@lcfd You use two different APIs here, mobility and tourism... that is maybe the problem. Could you provide some api calls here, that show the differences? If the merged api calls still do not show coordinates, then it is OK to remove the link completely. So I will wait for your examples before I merge the PR.

**Comment by lcfd** [comment]
@Piiit Ok that can be the reason. I'm rendering the UI using this condition: `sdatatypes === undefined`.
Knowing this the problem is solved on our side, you can **proceed with the merge**.

Anyway if you want to use those API togheter in the future I recomment to unify the syntax. It is really missleading.

**Comment by Piiit** [comment]
These are two different APIs in a micro-service world... we try to make them similar but we will have more and more APIs in the future which have all there own "dialect"... We cannot control them all fully...

**Comment by GnuRant** [comment]
@Piiit review!
