### ISSUE TITLE
"Directions" link is shown even if the disabled flag is set, for some stations

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-parking#21]

**Comment by lcfd** [comment]
@Piiit Hi, can you explain more extensively the problem and the outcome that we want to obtain?
What do you mean when you say ", for some stations"?

@gnurant fyi

**Comment by Piiit** [comment]
@lcfd  "For some stations" means, not for all... some are working correctly others not, please test and find the culprits. I guess the ones that are coming from one API have this behavior, where the others have not... It seems that the gray ones show this problem, whereas the green ones are correct. Please verify

**Comment by GnuRant** [comment]
@Piiit review!
