### ISSUE TITLE
Searching "fiera" returns wrong results

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-parking#29]
This is because the call has two "?" inside which is wrong

@lcfd Please check all queries, I have seen it only in one, but it is possible to be also in others.... Please try to test more and send PRs which are tested, otherwise this is a lot of work... Thank you

**Comment by lcfd** [comment]
I've tried them many times while working, no sign of error.

![Screenshot 2021-04-27 at 16 47 10](https://user-images.githubusercontent.com/9001053/116261770-42966a00-a778-11eb-8d54-24c461657377.png)

PR reviews exist for some reason

Anyway, I'll check the code

**Comment by Piiit** [comment]
Example: https://tourism.opendatahub.bz.it/api/Poi?pagenumber=1&poitype=64&subtype=2&pagesize=-1?searchfilter=fiera

**Comment by Piiit** [comment]
@lcfd That is ok to check PR with reviews, just wanted to say that they came in very fast and I found so many issues... nevertheless, all fine, we are nearly done now ...
