### ISSUE TITLE
Some enhancement suggestions for next version

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/webcomp-parking#32]
We are thinking about to integrate the webcomponent on suedtirol.info, on the detail pages of the cities.
Here are some suggestions for optimizations:

- [x] 1. Zoom level as configuration option
There is already the option of insert gps-coordinates that the map has to be centered on, but it would be nice if the page could also be zoomable on a certain level. In this way we could zoom on the city.

- [x] 2. (**ignored; see comments below**) Directions-link should open the Routeplanner instead of Google
Don't know if it's possible, but it would be awsome if the two webcomponents could be linked...

- [x] 3. Grey icon is not really visible
There is [already an issue](https://github.com/noi-techpark/webcomp-parking/issues/23) for this.

- [x] 4. (**postponed; see comments below**) Integrate public transport information for each parking (eg. next bus station, bus line, ecc.)
We suggest to show also the bus stations ecc. that are near to the parking lots.

- [x] 5. “Last update” only if real time data
In the detail-overlay of the parking lots there's always the label "last update" but the data is always an old one if it's not real time. We suggest to hide this information if there is no real time data.

- [x] 6. What’s the tourism data shown in the map?
In the configuration tool of the Webcomponents Store there is the field "Set the datasets to use in the component. Default is '["tourism", "mobility"]' ". It's not clear, which tourism data is used on the map.

**Comment by Piiit** [comment]
@niettadesantis 

> 1.

Number 1 done :-) See https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff?from=%2Fsearch%2Fparking

Feedback welcome

> 2. Directions-link should open the Routeplanner instead of Google

Which address exactly? Do you have it installed somewhere?

> 3. Grey icons

Which color do you like to have? Do you have the icon already?

> 4. 

I need to see what is possible. Maybe we need a dedicated issue for that, since it seems to be a major effort

> 5.
> 6.
I will solve these issues asap

**Comment by Piiit** [comment]
@niettadesantis @sseppi 
I had a look at no.6: 
- "tourism" means static data, without real time information which comes from the tourism API (at the moment they are the grey icons)
- "mobility" means real time data, from the mobility API (green icons)

I suggest to remove this option and always show all parking lots. I no longer see a reason why we should give an option to remove a part of the data.

What do you think?

**Comment by Piiit** [comment]
@niettadesantis Fixed the grey icons as well... no.3

Now all icons are green, but the parking lots with a real time update have now a pulsing dot... Let me know if you like it

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff

See stations in/near Bolzano for such dots.

I thought, that for those who search parking lots, it is not important to know if the data provided is realtime or not (at least not that important) therefore I opted for a design that is not so focused on measurement types of parking lots, but just about positions on a map.

**Comment by ohnewein** [comment]
@Piiit the pulsing icons are cool! I am not sure about the color. In my view parking should be blue, green gets confused with e-charging stations. @niettadesantis and @rcavaliere what do you think?

**Comment by rcavaliere** [comment]
@ohnewein I like the enhancements too! I agree with you: parking is always associated to a blue colour, using something different would be strange for the user

**Comment by niettadesantis** [comment]
Thank you very much @Piiit! Here's my feedback to the points so far:

1.
> Number 1 done :-)

Perfect, thanx!

2.
> Which address exactly? Do you have it installed somewhere?

Just forget this point... the more I think about it, the more I realize, it's not feasible... or at least it would be too much effort.

3.

> Now all icons are green, but the parking lots with a real time update have now a pulsing dot... Let me know if you like it

As Patrick and Roberto already wrote, blue would be better for me too.

> I thought, that for those who search parking lots, it is not important to know if the data provided is realtime or not (at least not that important) therefore I opted for a design that is not so focused on measurement types of parking lots, but just about positions on a map.

You're right, that's also my opinion. The only thing is: if you implement a new icon (with pulsing dot) you have to explain it somewhere (in a legend for example).

6.

> I suggest to remove this option and always show all parking lots. I no longer see a reason why we should give an option to remove a part of the data.
> What do you think?

Yes, I would remove it too.

**Comment by Piiit** [comment]
@ohnewein @rcavaliere @niettadesantis 

Now the icons are blue, and option no.6 has been removed...

I will now also add a information somewhere about what the pulsing dot means, I still have to think about it

**Comment by Piiit** [comment]
@niettadesantis 
> You're right, that's also my opinion. The only thing is: if you implement a new icon (with pulsing dot) you have to explain it somewhere (in a legend for example).

I added a "key" to the detail view... just open a pulsing dot icon

**Comment by Piiit** [comment]
@niettadesantis @rcavaliere @ohnewein 

For no.4 to work we need to finalize the OTP project first. Roberto, please correct me if I am wrong, but we do not have data about bus stops/lines at the moment to be used inside a web component, right?

The public transport web component never got to a production ready state, and OTP is still not ready...

**Comment by Piiit** [comment]
@niettadesantis Please test... see updates inside first comment for skipped tasks

**Comment by rcavaliere** [comment]
@Piiit now we have the public transportation data via API, and this is sufficient stable for starting with such an integration... but maybe it's better to add the public transportation info with a next release of this web component. More details during the Sprint Meeting on Friday

**Comment by niettadesantis** [comment]
> I added a "key" to the detail view... just open a pulsing dot icon

The key is great, I would suggest this translations:
EN:
Legend
Real time data

DE:
Legende
Echtzeitdaten

IT:
Leggenda
Dati in tempo reale

And maybe you could add also a tool tip on the pulsing pin icon?

**Comment by niettadesantis** [comment]
Another input: when I click on the filter icon, I can filter the results by "Only show parking spaces with available spots".
This filter basically does nothing, it shows always the same results. Maybe it should be modified like this:
"Only show parking spaces with real time data" and by checking it we should show only the parking spaces with real time data.
What do you mean?

**Comment by Piiit** [comment]
@niettadesantis @rcavaliere I fixed the translations now, for your new suggestions please create separate user stories (backlogged)... so that I can tackle them one-by-one and prioritize with other tasks I have... This sprint I do not have time anymore... 

Thank you for your understanding :-)

If you agree, I will also put this changes into production... Just move it to the corresponding column if you like

**Comment by Piiit** [comment]
Wow that was fast ;-) 

Will be online in no-time ...
