### ISSUE TITLE
Rethink the feature "currentLocation"

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-parking#6]
**UPDATE 2021-01-26**
- [ ] The current position always overrides the former one, cancelling the old point on the map
- [x] We will for now keep the json object notation, and eventually open a new issue if feedback is negative about that 
- [ ] The store has a bug, that prevents double-quotes, this should be solved by @Piiit 

**ALL DEPRECATED BELOW**
It seems that the coordinates are not replicated on the map, however if I select my current location it works. Are they set correctly from within the store?

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff

**UPDATE 2021-01-20**
The coordinates work now if set like `currentLocation='{ "lat": 4.31, "lng": 1.26 }'`, that is with single quoted JSON object.

Several issues exist with that feature:
-  The json object notation is not easily understandable for web component users, this should be easier to access
-  If we activate the current location of the browser, we have two location markers... I would use one of the following two possibilites to solve that:
   -   they should either be with a different style or/and have a label --> for example to always show a certain hotel, that has a for example red dot marker with the label "Hotel ABC" and the real current position marker should be kept as is (I would call the attribute then just "latitude", "longitude", "location-label")
   - the real current position overwrites the manually given one or vice-versa, we need to decide which one has precedence

@sseppi @GnuRant @lcfd What do you think? Please comment below... The decisions should then be merged into all web-components with this feature.

**Comment by Piiit** [comment]
@GnuRant FYI

**Comment by lcfd** [comment]
@Piiit I'll give it a look

**Comment by Piiit** [comment]
@sseppi @GnuRant @lcfd I have change the initial comment, please have a look

**Comment by lcfd** [comment]
@Piiit 

> The json object notation is not easily understandable for web component users, this should be easier to access

This is how lit-element works, I haven't found other ways to pass down objects.

Can't understand the second point, the component should be as in the approved design. @GnuRant

**Comment by Piiit** [comment]
> @Piiit
> 
> > The json object notation is not easily understandable for web component users, this should be easier to access
> 
> This is how lit-element works, I haven't found other ways to pass down objects.

That is exactly the issue, I would not pass down objects here.

> 
> Can't understand the second point, the component should be as in the approved design. @GnuRant

The issue is that we have two position markers, we need to decide on the precedence if we do not want to show both. Or, make them distinguishable if we want to keep them

**Comment by lcfd** [comment]
@Piiit Ok, for the second point the system integrator has the priority. We aren't using the GPS on the startup of the component. We are using it only on the user press of the centering position button.

**Comment by lcfd** [comment]
@sseppi

As said in call this is a problem with the web component store way of use HTML parameters.
This issue is linked to the decision of maintain this semantic lit-element w.c. way or split the parameter in two.

cc @GnuRant
