### ISSUE TITLE
Some configurations are missing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-parking#8]
According to the Briefing sent some configurations of the web component on the web component store are missing.

In particular actually for a web component store user are missing the following configuration opportunity:
- [x] select which parking houses to show on the map;
- [x] activate/deactivate the real time information;
- [x] activate/deactivate the forecast information;
- [x] activate/deactivate the “get directions” button.

@GnuRant

**Comment by lcfd** [comment]
@GnuRant

**Comment by lcfd** [comment]
@sseppi 

Point 2,3 and 4 are in PR.
Point 1 should also be, but I don't know if we are thinking about the same thing. Is it the parameter that allow the sys int. to select which dataset to use? I've created this parameter `enabledParkingData='["tourism", "mobility"]'` that I think solve the issue. Let me know.

cc @gnurant

**Comment by Piiit** [comment]
@dulvui please have a look at this, and please accept the invitation https://github.com/noi-techpark/webcomp-parking/invitations

That is test the functionalities mentioned in the first comment, and eventually accept new PRs for this repo... add issues and eventually comment here if needed

**Comment by sseppi** [comment]
@lcfd for the point 1 it would be perfect if you could add also the possibility to select one or more parking lots by using the parking lot IDs.

**Comment by dulvui** [comment]
Ho caricato una nuova versione (v1.0.1) con la ultima PR nel test webstore

**Comment by Piiit** [comment]
@dulvui Perfect, thank you
