### ISSUE TITLE
The "tourism" parking lots are missing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-parking#9]
Looking to the actual version of the web component it seems that all parking lots without real time information are missing.
The parking lots provided by the following call on the Tourism Open Data hub:
http://tourism.opendatahub.bz.it/api/Poi?pagenumber=1&pagesize=10&poitype=64&subtype=2

**Comment by lcfd** [comment]
I'm using the same endpoint for every station, if there are no data it's a matter of availability.
I can check if the endpoint is misused and has unnecessary parameters.

For the next issues remember to tag @GnuRant also.

**Comment by sseppi** [comment]
As agreed during the kick off meeting we do have PArking lots that has real time information (the one of the ODH mobility) and other that hasn't real time information (the one ot the ODH Tourism).

In the first case all information (real time, forecast and static info) has to be shown, in the second one only static info (Name, Address, description, etc.) has to be shown.

**Comment by lcfd** [comment]
@sseppi ok, now it's more clear.
We will add it to the backlog.

**Comment by lcfd** [comment]
Hi, @sseppi. The endpoint in the main comment has no way to get all the POI in the same request.
I've tried with `pagesize=1000` and `availabilitycheck=true`, but they both aren't working and there's no error.
The limit of 10 elements per page is mantained. 
Suggestions?

CC @Piiit @RudiThoeni

**Comment by lcfd** [comment]
If I set pagesize to -1 the totalpages are: ` TotalPages: -394,`
But apparently it's working.

**Comment by RudiThoeni** [comment]
http://tourism.opendatahub.bz.it/api/Poi?pagenumber=1&pagesize=1000&poitype=64&subtype=2

i get 394 results on one page?

**Comment by lcfd** [comment]
@RudiThoeni 
ok, it's not that future proof, but I'll set pagesize to 1000

**Comment by lcfd** [comment]
@sseppi @Piiit 

This issue is in PR

cc @gnurant
